;; 上流 CSS の再 vendor(nbb)。digital-go-jp/design-system-example-components-html。
;; usage(repo root から): nbb scripts/vendor.cljs <path-to-upstream-clone>
;; 生成物: resources/jp_go_dds/dds.css(冒頭に upstream commit + MIT 表記) + LICENSE-upstream

(require '["fs" :as fs]
         '["path" :as path]
         '["child_process" :as cp])

(def components
  ;; 上流 41 エントリのうち、正式コンポーネント(c/c.css を持つ)は 40、
  ;; card だけがパターン(example CSS のみ)なので vendor できない。
  ;; ここに名前を足して再 vendor すれば増やせる。
  ["button" "heading" "accordion" "input-text" "textarea" "checkbox"
   "form-control-label" "table" "chip-label" "divider" "notification-banner"
   ;; select: フォームの必須部品。以前「上流に無い」と誤認して各 app が
   ;; 自前 CSS を書いていた(実際は vendor していなかっただけ)。
   "select"
   ;; link / list: skin が素の a / ul,ol,li を自前で塗っていた分を公式へ寄せる。
   "link" "list"])

(let [[upstream] *command-line-args*]
  (when-not (and upstream (fs/existsSync upstream))
    (println "usage: nbb scripts/vendor.cljs <path-to-upstream-clone>")
    (js/process.exit 2))
  (let [sha (-> (cp/execSync "git rev-parse HEAD" #js {:cwd upstream}) .toString .trim)
        header (str "/* jp-go-digital-design-system — vendored CSS\n"
                    " * Source: https://github.com/digital-go-jp/design-system-example-components-html\n"
                    " * Upstream commit: " sha " — MIT License, Copyright (c) 2025 デジタル庁\n"
                    " * Generated by scripts/vendor.cljs — DO NOT EDIT BY HAND (re-vendor instead). */\n")
        css (apply str header
                   (fs/readFileSync (path/join upstream "src/global.css") "utf8")
                   (for [c components]
                     (str "/* --- component: " c " --- */\n"
                          (fs/readFileSync (path/join upstream "src/components" c (str c ".css")) "utf8"))))]
    (fs/writeFileSync "resources/jp_go_dds/dds.css" css)
    (fs/copyFileSync (path/join upstream "LICENSE") "LICENSE-upstream")
    (println "vendored at upstream" sha "->" (count css) "bytes")))
