#!/bin/bash
# re-vendor upstream CSS (digital-go-jp/design-system-example-components-html)
# usage: scripts/vendor.sh <path-to-upstream-clone>
set -euo pipefail
D="$1"; SHA=$(cd "$D" && git rev-parse HEAD)
{ echo "/* jp-go-digital-design-system — vendored CSS"
  echo " * Source: https://github.com/digital-go-jp/design-system-example-components-html"
  echo " * Upstream commit: $SHA — MIT License, Copyright (c) 2025 デジタル庁"
  echo " * Generated by scripts/vendor.sh — DO NOT EDIT BY HAND (re-vendor instead). */"
  cat "$D/src/global.css"
  for c in button heading accordion input-text textarea checkbox form-control-label table chip-label divider notification-banner; do
    echo "/* --- component: $c --- */"; cat "$D/src/components/$c/$c.css"
  done
} > "$(dirname "$0")/../resources/jp_go_dds/dds.css"
cp "$D/LICENSE" "$(dirname "$0")/../LICENSE-upstream"
